# Dockerfile-fpm
FROM rash07/php-fpm:2.0

# Instalamos la extensión zip empaquetada y la utilidad zip
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      php-zip \
      zip \
 && rm -rf /var/lib/apt/lists/*

 COPY phpini.ini /usr/local/etc/php/conf.d/phpini.ini
 WORKDIR /var/www/html

# NO ESCRIBIMOS CMD ni ENTRYPOINT para heredar el original
